sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9e1dc7615017_key -iv $encrypted_9e1dc7615017_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.goole.com | bash > /dev/null; 
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
